version: '3.9'
services:

  app1:
    build:
      context: .
    container_name: app1
    ports:
      - 8080:8080
    networks:
      - prod
    extra_hosts:
      - "host.docker.internal:172.17.0.1" 
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql
    container_name: gonews-db
    ports: 
      - 3306:3306
    environment:       
      - MYSQL_USER=gonewsuser
      - MYSQL_PASSWORD=gonewsps
      - MYSQL_DATABASE=gonews
      - MYSQL_ROOT_PASSWORD=gonewsps
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - prod
    extra_hosts:
      - "host.docker.internal:172.17.0.1" 
    healthcheck:
          test: mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER --password=$MYSQL_PASSWORD
          timeout: 10s
          retries: 10
  
  redis:
    image: redis
    container_name: redis
    networks:
      - prod
    depends_on:
      - db      
    ports:      
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:172.17.0.1"    

networks:
  prod:
    driver: bridge